name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test Docker image
        run: |
          docker build --target test -t my-test-image .
          docker run my-test-image
